FROM gcr.io/google-samples/microservices-demo/frontend:v0.8.0
LABEL org.opencontainers.image.revision="${CI_COMMIT_SHORT_SHA:-local}" \
      org.opencontainers.image.source="https://gitlab.example/your/repo"